### ISSUE TITLE
Bug report: Closing a dropdown causes scrolling

### ISSUE THREAD

**Issue by thrashr888** [hashicorp/design-system#267]
## IS: Current behavior

When you open a dropdown, scroll away, then open another, the page scrolls back to the first dropdown when closing it.

## SHOULD BE: Expected behavior

The page should not scroll away so I can retain my context and awareness of what I'm doing.

## Steps to reproduce

1. https://design-system-components-hashicorp.vercel.app/components/dropdown
2. click the text toggle dropdown
3. scroll down
4. click the gear dropdown

**Comment by didoo** [comment]
@thrashr888 thanks for submitting this issue. I noticed it myself, but I am not sure if it's a bug or a "feature". The reason why the page scrolls is because the focus is returned to the element that initially "opened" the dropdown (the first one) on click-outside, and Chrome scrolls to bring back the focused element in the viewport (while if you test this in Safari, it works as you say you would expect) which in this case is the `toggle` element of the first dropdown.

@MelSumner any thoughts on this?

**Comment by thrashr888** [comment]
I sort of follow, but should clicking on a new thing focus on that instead? I think that even when clicking on whitespace, I wouldn't expect to scroll back up from that.

**Comment by MelSumner** [comment]
@thrashr888 I'm going to dig through the ember-focus-trap/focus-trap docs to see if this is documented; then I'll try to document potential solutions.
