### ISSUE TITLE
dropdown: consider supporting error state for copy-item

### ISSUE THREAD

**Issue by MelSumner** [hashicorp/design-system#275]
in the copy-item component, we have a success state that indicates that the item has been successfully copied. We do not have anything to indicate that the copy was not successful. Is this something we want to consider?

**Comment by didoo** [comment]
@MelSumner if @heatherlarsen can provide the color styles for the "error" state, I think having also this state could be easy to achieve. Not a blocker and not urgent, though.

**Comment by heatherlarsen** [comment]
This was a temporary solution to aid in the migration of the dropdown and was not intended to be a full-fledged component, so I don't find value in prioritizing the design work for this.

I realized because of the text input audit that previous versions of this pattern are actually using a read-only input field with added click-to-copy functionality, not a button as was coded for the dropdown implementation. In some instances, the read-only field seems like the correct usage (when the data also needs to be passed in a form), but in the dropdown it seems like the incorrect usage. That aside, this shows that because we haven't done a formal audit, there are some unknowns about the use cases, intended behaviors, etc. I'd hold off on doing any additional work on the copy-item component until we're able to prioritize an audit and focus our efforts on holistically understanding the various types of click-to-copy and copy item features available in all the products.
