### ISSUE TITLE
Flight icon request: hex-numerical-one, hex-numerical-two, hex-numberical-three

### ISSUE THREAD

**Issue by kaxcode** [hashicorp/design-system#465]
**Outline the use case for the new icon.**
We would like to update the [icons in our Onboarding Stepper](https://github.com/hashicorp/cloud-ui/blob/master/engines/consul/addon/components/onboarding-stepper/step-icon/index.hbs), but we need the numerical versions to proceed.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
N/A

**Describe alternatives you've considered.**
N/A

**Screenshots**
`hcp/public/svgs/hex-numerical-one.svg`
![Screen Shot 2022-07-19 at 11 42 26 AM](https://user-images.githubusercontent.com/19161242/179792394-aca4c700-1da2-4642-b1c2-368a3c1cb69b.png)

`hcp/public/svgs/hex-numerical-two.svg`
![Screen Shot 2022-07-19 at 11 42 47 AM](https://user-images.githubusercontent.com/19161242/179792398-5f56a285-7b16-4de3-bebe-b2bb9e4e8894.png)

`hcp/public/svgs/hex-numerical-three.svg`
![Screen Shot 2022-07-19 at 11 43 00 AM](https://user-images.githubusercontent.com/19161242/179792396-7711ad92-8b65-4773-b834-90485f121460.png)

**Figma**
Add links to the relevant Figma files where this icon is used, if possible.
[Figma frame
](https://www.figma.com/file/XehMezwXmaByBUcBsZy50B/HCP-Consul---Activation-I---Guided-Onboarding?node-id=6568%3A61881)

**Additional context**
Add any other relevant context.

**Comment by jorytindall** [comment]
@kaxcode we're currently working on a new component that fits the role of a stepper indicator which overlaps a significant amount with this request. Since this is more related to stepper/onboarding components and patterns a new Flight icon probably isn't as suited in this scenario (what do you think @cveigt ?). 

The stepper indicator is in progress right now, but covers a variety of different use cases including a variant for non-interactive steps/content. More documentation [here](https://docs.google.com/document/d/1ULRVzVDL2xrpgNoxINBMB4QwgJ_NyptI60x-2-YkFNg/edit?usp=sharing). I'll connect with you to understand individual requirements and use cases.

**Comment by kaxcode** [comment]
Since, the Stepper Indicator component work scopes these icons, I will close this issue.
