### ISSUE TITLE
Flight icon request: [test-connection]/[test]

### ISSUE THREAD

**Issue by evankerrigan** [hashicorp/design-system#53]
### Outline the use case for the new icon.
Users will soon be able to connect an entity from within the HashiCorp Platform (a cluster in the initial instance) to an external system (third-party log management applications) so that data will flow in real-time from HCP to the external providers. As part of the configuration flow, we’ll be offering users the ability to verify that 1️⃣ they’ve entered the correct information and 2️⃣  that the HCP is able to send data to the other system _before_ committing what they’ve entered. We’ll need some way to help reinforce this testing functionality visually for users.

The description here is specific to its first use, but both @snehahash and @luoxuan00733 have mentioned that it might be useful for other similar networking-relating scenarios.

### If there's a similar existing icon, why isn't it a good fit? Please describe.
I couldn’t find an existing icon that suggests verifying something that could either succeed or fail — the closest related ones seem to imply what the status _is_ rather than checking to see what it could be.

### Describe alternatives you've considered.
- Initially, there was no icon associated with this button, but given [the upcoming recommendation for tertiary buttons](https://docs.google.com/presentation/d/1RAMGan0nlF4-SiyPzBDqS7x71JF05MAw8H5ghMyzkuI/edit#slide=id.g11756e74060_0_4408), an icon will now be required. 
- While most of the scenarios that have been compiled so far have been for testing connectivity between two a HashiCorp system and an external one, there might be other “pre-flight checking” scenarios that aren’t networking-related, and so perhaps a more generic “test” icon might be another alternative to one explicitly for network connections.

### Screenshots
_An icon-less “Test connection” button for audit log streaming_

<img width="1440" alt="test-connection" src="https://user-images.githubusercontent.com/70760/157974973-89991463-a96f-4f3d-994f-4d11c534f655.png">

### Figma
[Audit log streaming designs](https://www.figma.com/file/k08dy2DBhWhXl0LgOAzAu4/?node-id=3926%3A13083) 

### Additional context
N/A

**Comment by cveigt** [comment]
I worked on a few options and narrowed them down to the two I'm sharing below and I'm curious to know what you do you think

<img width="245" alt="Screen Shot 2022-04-27 at 6 47 51 PM" src="https://user-images.githubusercontent.com/2142312/165659925-e9e8cc16-0d0d-4e92-9317-017afdeed5f0.png">

Here a couple of screens from your file so that you can see them working in context

<img width="1440" alt="icon-test01" src="https://user-images.githubusercontent.com/2142312/165660167-9d3083b5-1d98-46e9-8fce-d734a1c1869b.png">
<img width="1440" alt="icon-test02" src="https://user-images.githubusercontent.com/2142312/165660175-8d296bcd-5650-4070-ae4c-c34562b3d870.png">

Another alternative you could consider is using the **[connection](https://flight-hashicorp.vercel.app/?query=connect)** icon.
![Screen Shot 2022-04-27 at 6 51 15 PM](https://user-images.githubusercontent.com/2142312/165660326-db6c20a4-6cb8-4967-aeb1-c36cb2d5f0f1.png)

This is the [branch](https://www.figma.com/file/MYiw4kiVpunIMMw0sBkE1t/branch/WOpPShLejroYaDrn07GEUN/%E2%9C%8F%EF%B8%8F-Flight-Development?node-id=205%3A0) I'm working in if you want to test them. _Just note that they are WIP and are not polished yet_

**Comment by evankerrigan** [comment]
Wow, thanks for the great options, @cveigt! 🤩

I think among the three choices you included here, I think this one would work the best: 

<img width="123" alt="check-test" src="https://user-images.githubusercontent.com/70760/165838325-e97652db-9e5c-42bd-91c0-8f88e93e76c6.png">


### Rationale _for_ the “dashed check” option

- It’s a bit more legible, particularly at the smaller scale
- The dashed outline affords a sense of incompleteness — which seems to fit well with testing a connection (maybe it could fail!)
- It pairs nicely with [the existing `delay` icon](https://flight-hashicorp.vercel.app/?query=delay) (which has a “synonym” of `queue`): sure, the system has scheduled this thing to happen, but it might not happen if there’s a problem — once again this fits nicely with testing


### Rationale against the “checklist” option

- A bit less legible, especially at smaller sizes
- The appearance of the “×” at the bottom of the list might give the mistaken impression that something has already failed (”Wait… was it testing the connection this whole time? Do I need to fix something?”)


### Rationale against the “connection” option

- This icon might give the impression that the connection has already happened

**Comment by cveigt** [comment]
According to what was discussed with @evankerrigan on Slack, we will go with the option below for now

<img width="122" alt="Screen Shot 2022-04-29 at 6 09 02 PM" src="https://user-images.githubusercontent.com/2142312/166084634-3dd37344-cfdb-4908-9512-28a8aad0894b.png">

It's been added to the main file but hasn't been published yet.
@didoo there's one, probably two more icons I will be working on next sprint so I think we can release them all together.
